# docker-compose.yml
version: "3"
services:
  frontend:
    build: ./react-frontend
    ports:
    - "80:3000"

  backend:
    build: ./laravel-backend
    depends_on:
    - db
    ports:
    - "8080:8000"
    environment:
      DATABASE_HOST: db
      DATABASE_PASSWORD: pa55word
      DATABASE_NAME: public
      DATABASE_USERNAME: admin

  db:
    build: ./database
    environment:
      MYSQL_PASSWORD: pa55word
      MYSQL_DATABASE: public
      MYSQL_USER: admin
    ports:
    - "3306:3306"

